# mysql数据库地址，默认为时本地地址127.0.0.1，如果是要连接远程数据库才需要更改
db_host: 127.0.0.1
# mysql数据库连接端口，默认3306，一般不用改
db_port: 3306
# 数据库名称，默认为image_database
db_name: word_web
# 数据库用户名
db_username: root
# 数据库密码
db_password: srx62600
# 服务器host，如果是发布到服务器上就填0.0.0.0，如果是在自己本机上跑都直接默认的127.0.0.1就可以了
server_host: 127.0.0.1
# 服务器port，选择一个自己服务器【本机】上没有被占用的端口即可，默认5555
server_port: 5656




